spring:
  jpa:
    generate-ddl: false
  datasource:
    platform: mysql
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:3306/llama"
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    initialization-mode: ALWAYS

security:
  google-url: "https://www.googleapis.com/oauth2/v3/tokeninfo"
  google-client_id: ${GOOGLE_CLIENT_ID}
  google-secret-key: ${GOOGLE_SECRET_KEY}

parameters:
  user:
    start-coins: 0
    start-level: 0
  items:
    max: 100
  captures:
    time-unit: MINUTES
    time-value: 3
    time-unit-first: SECONDS
    time-value-first: 10
    max: 20
  creatures:
    max: 250
    chance-female: 50
    energy-time-unit: SECONDS
    energy-time-value: 3
    price:
      gen-1: 1
      gen-2: 5
      gen-3: 10
      gen-4: 15
      gen-5: 20
      gen-6: 25
      gen-7: 30
      gen-8: 35
      gen-9: 40
      gen-10: 45
      gen-11: 50
  genes:
#    chance-quality-1: 1
    chance-quality-1: 50
    chance-quality-2: 10
    chance-quality-3: 20
    chance-love: 30
    chance-hunger: 30
    chance-thirst: 30
    chance-fertile: 10
    special-chance: 20
    special-chance-quality-1: 20
    special-chance-quality-2: 25
    special-chance-quality-3: 30
  pens:
#    item-activation-chance: 20
    item-activation-chance: 50
    price:
      size-4: 1
      size-5: 1
      size-6: 1
      size-7: 1
      size-8: 1
      size-9: 1
      size-10: 1
      size-11: 1
      size-12: 1
      size-13: 1
      size-14: 1
      size-15: 1
      size-16: 1
      size-17: 1
      size-18: 1
      size-19: 1
      size-20: 1
