spring:
  jpa:
    generate-ddl: false
#    properties:
#      hibernate:
#        show_sql: true
#        use_sql_comments: true
#        format_sql: true
  datasource:
    platform: mysql
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:3306/llama"
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    initialization-mode: ALWAYS

security:
  google-url: "https://www.googleapis.com/oauth2/v3/tokeninfo"
  google-client_id: ${GOOGLE_CLIENT_ID}
  google-secret-key: ${GOOGLE_SECRET_KEY}

parameters:
  user:
    start-coins: 0
    start-level: 0
  items:
    max: 100
  captures:
    time-unit: HOURS
    time-value: 1
    time-unit-first: SECONDS
    time-value-first: 5
    max: 20
  creatures:
    max: 250
    chance-female: 50
    chance-cross-breed: 20
    chance-bi-color: 50
    max-babies: 1
    energy-time-unit: SECONDS
    energy-time-value: 30
    pregnancy-time-unit: MINUTES
    pregnancy-time-values:
      gen-1: 5
      gen-2: 60
      gen-3: 120
      gen-4: 180
      gen-5: 300
      gen-6: 480
      gen-7: 720
      gen-8: 1440
    maturity-increments:
      gen-1: 500
      gen-2: 50
      gen-3: 25
      gen-4: 15
      gen-5: 15
      gen-6: 10
      gen-7: 10
      gen-8: 5
    energy-increments:
      gen-1: 100
      gen-2: 10
      gen-3: 5
      gen-4: 3
      gen-5: 3
      gen-6: 2
      gen-7: 2
      gen-8: 1
    stats-increments:
      gen-1: 5
      gen-2: 3
      gen-3: 3
      gen-4: 3
      gen-5: 2
      gen-6: 2
      gen-7: 2
      gen-8: 2
    prices:
      gen-1: 1
      gen-2: 2
      gen-3: 4
      gen-4: 8
      gen-5: 15
      gen-6: 30
      gen-7: 60
      gen-8: 100
  genes:
    chance-quality-0: 10
    chance-quality-1: 20
    chance-quality-2: 30
    chance-quality-3: 40
    chance-love: 25
    chance-hunger: 25
    chance-thirst: 25
    chance-fertile: 25
    special-chance-quality-1: 20
    special-chance-quality-2: 25
    special-chance-quality-3: 30
  pens:
    activation-time-unit: SECONDS
    activation-time-value: 30
    item-activation-chance: 100
    price:
      size-4: 1
      size-5: 1
      size-6: 1
      size-7: 1
      size-8: 1
      size-9: 1
      size-10: 1
      size-11: 1
      size-12: 1
      size-13: 1
      size-14: 1
      size-15: 1
      size-16: 1
      size-17: 1
      size-18: 1
      size-19: 1
      size-20: 1
