spring:
  jpa:
    generate-ddl: false
#    properties:
#      hibernate:
#        show_sql: true
#        use_sql_comments: true
#        format_sql: true
  datasource:
    platform: mysql
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:3306/llama"
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    initialization-mode: ALWAYS

security:
  firebase-credentials: ${FIREBASE_CREDENTIALS}

parameters:
  user:
    start-coins: 0
    start-level: 0
  items:
    max: 100
  captures:
    time-unit: MINUTES
    time-value: 15
    time-unit-first: SECONDS
    time-value-first: 5
    time-unit-net: HOURS
    time-value-net: 3
    max: 10
  creatures:
    max: 250
    chance-female: 50
    chance-cross-breed: 30
    chance-bi-color: 50
    max-babies: 1
    energy-time-unit: SECONDS
    energy-time-value: 30
    pregnancy-time-unit: MINUTES
    pregnancy-time-values:
      gen-1: 5
      gen-2: 20
      gen-3: 60
      gen-4: 120
      gen-5: 240
      gen-6: 480
      gen-7: 720
      gen-8: 1440
    maturity-increments:
      gen-1: 500
      gen-2: 250
      gen-3: 83
      gen-4: 55
      gen-5: 55
      gen-6: 40
      gen-7: 27
      gen-8: 20
    energy-increments:
      gen-1: 100
      gen-2: 50
      gen-3: 16
      gen-4: 11
      gen-5: 11
      gen-6: 8
      gen-7: 5
      gen-8: 4
    stats-increments:
      gen-1: 5
      gen-2: 3
      gen-3: 3
      gen-4: 3
      gen-5: 2
      gen-6: 2
      gen-7: 2
      gen-8: 2
    prices:
      gen-1: 1
      gen-2: 2
      gen-3: 4
      gen-4: 8
      gen-5: 15
      gen-6: 30
      gen-7: 60
      gen-8: 100
  genes:
    chance-quality-0: 0
    chance-quality-1: 10
    chance-quality-2: 20
    chance-quality-5: 30
    chance-quality-8: 40
    chance-love: 27
    chance-hunger: 27
    chance-thirst: 27
    chance-cresus: 19
    special-chance-quality-1: 10
    special-chance-quality-2: 20
    special-chance-quality-5: 25
    special-chance-quality-8: 30
  pens:
    activation-time-unit: SECONDS
    activation-time-value: 30
    item-activation-chance: 100
    prices:
      pen-1:
        size-3: 0
        size-4: 20
        size-5: 40
        size-6: 80
      pen-2:
        size-3: 150
        size-4: 300
        size-5: 600
        size-6: 1000
