spring:
  jpa:
    generate-ddl: false
  datasource:
    platform: mysql
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:3306/llama"
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    initialization-mode: ALWAYS

security:
  google-url: "https://www.googleapis.com/oauth2/v3/tokeninfo"
  google-client_id: ${GOOGLE_CLIENT_ID}
  google-secret-key: ${GOOGLE_SECRET_KEY}

parameters:
  user:
    start-coins: 0
    start-level: 0
  items:
    max: 100
  captures:
    time-unit: MINUTES
    time-value: 15
    time-unit-net: HOURS
    time-value-net: 4
    time-unit-first: SECONDS
    time-value-first: 5
    max: 20
  creatures:
    max: 250
    chance-female: 50
    chance-cross-breed: 20
    chance-bi-color: 50
    max-babies: 2
    energy-time-unit: MINUTES
    energy-time-value: 1
    pregnancy-time-unit: MINUTES
    pregnancy-time-values:
      gen-1: 5
      gen-2: 60
      gen-3: 120
      gen-4: 180
      gen-5: 300
      gen-6: 480
      gen-7: 720
      gen-8: 1440
    maturity-increments:
      gen-1: 2000
      gen-2: 100
      gen-3: 50
      gen-4: 25
      gen-5: 12
      gen-6: 8
      gen-7: 5
      gen-8: 4
    energy-increments:
      gen-1: 200
      gen-2: 20
      gen-3: 10
      gen-4: 5
      gen-5: 5
      gen-6: 4
      gen-7: 3
      gen-8: 2
    stats-increments:
      gen-1: 5
      gen-2: 3
      gen-3: 3
      gen-4: 3
      gen-5: 2
      gen-6: 2
      gen-7: 2
      gen-8: 2
    prices:
      gen-1: 1
      gen-2: 10
      gen-3: 20
      gen-4: 40
      gen-5: 80
      gen-6: 160
      gen-7: 320
      gen-8: 640
  genes:
    chance-quality-0: 0
    chance-quality-1: 5
    chance-quality-2: 10
    chance-quality-3: 20
    chance-love: 30
    chance-hunger: 30
    chance-thirst: 30
    chance-fertile: 10
    special-chance-quality-1: 20
    special-chance-quality-2: 25
    special-chance-quality-3: 30
  pens:
    activation-time-unit: MINUTES
    activation-time-value: 1
    item-activation-chance: 100
    price:
      size-4: 1
      size-5: 1
      size-6: 1
      size-7: 1
      size-8: 1
      size-9: 1
      size-10: 1
      size-11: 1
      size-12: 1
      size-13: 1
      size-14: 1
      size-15: 1
      size-16: 1
      size-17: 1
      size-18: 1
      size-19: 1
      size-20: 1
